# Generated by Django 6.1.1 on 2026-09-08 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('origin_name', models.CharField(max_length=120)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('destination_name', models.CharField(max_length=120)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(default='Pupi Bus', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('ida', 'Metro -> EAFIT'), ('vuelta', 'EAFIT -> Metro')], default='ida', max_length=6)),
                ('status', models.CharField(choices=[('waiting', 'En espera'), ('in_progress', 'En curso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='waiting', max_length=12)),
                ('waiting_minutes', models.PositiveSmallIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='tracking.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='tracking.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='tracking.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='tracking.trip')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['trip', '-timestamp'], name='tracking_po_trip_id_db4c59_idx')],
            },
        ),
    ]
